name: ANOVA F-value
classifier:
  estimator:
    _target_: fseval.estimators.anova_f_value.ANOVAFValueClassifier
regressor:
  estimator:
    _target_: fseval.estimators.anova_f_value.ANOVAFValueRegressor
estimates_feature_importances: true