name: Boruta
classifier:
  estimator:
    _target_: fseval.estimators.boruta.Boruta
    estimator:
      _target_: sklearn.ensemble.RandomForestClassifier
    n_estimators: auto
  multioutput: false
estimates_feature_importances: false
estimates_feature_support: true
estimates_feature_ranking: true