name: XGBoost
classifier:
  estimator:
    _target_: xgboost.XGBClassifier
regressor:
  estimator:
    _target_: xgboost.XGBRegressor
multioutput: false
estimates_feature_importances: true
estimates_target: true