# @package _group_
_target_: mleval.datasrc.WandbArtifact
name: XOR (Chen et al.)
type: regression
multivariate: true
entity: dunnkers
artifact_id: dunnkers/msc-thesis-exploration/xor:v0
relevant_features:
  - 0
  - 1
  - 2
  - 3