name: Additive (Chen et al.)
group: Chen et al
task: regression
domain: synthetic
adapter:
  _target_: l2x_synthetic.AdditiveGenerator
  n_samples: 10000
  random_state: 0
feature_importances:
  X[:, 0:3]: 1.0