adapter:
  _target_: sklearn.datasets.make_classification
  class_sep: 0.9
  n_classes: 2
  n_clusters_per_class: 3
  n_features: 30
  n_informative: 3
  n_redundant: 0
  n_repeated: 0
  n_samples: 10000
  random_state: 0
  shuffle: false
domain: synthetic
feature_importances:
  X[:, 0:3]: 1.0
group: Synclf
name: Synclf medium
task: classification
