adapter:
  _target_: sklearn.datasets.make_classification
  class_sep: 1.0
  n_classes: 2
  n_clusters_per_class: 2
  n_features: 20
  n_informative: 2
  n_redundant: 0
  n_repeated: 0
  n_samples: 10000
  random_state: 0
  shuffle: false
domain: synthetic
feature_importances:
  X[:, 0:2]: 1.0
group: Synclf
name: Synclf easy
task: classification
