adapter:
  _target_: sklearn.datasets.make_regression
  bias: 200
  coef: false
  effective_rank: null
  n_features: 10
  n_informative: 2
  n_samples: 10000
  n_targets: 1
  noise: 0
  random_state: 0
  shuffle: false
domain: synthetic
feature_importances:
  X[:, :]:
  - 0.6696632156761879
  - 0.3303367843238121
  - 0.0
  - 0.0
  - 0.0
  - 0.0
  - 0.0
  - 0.0
  - 0.0
  - 0.0
group: Synreg
name: Synreg easy
task: regression
