project: toy-wandb-fs
task:
  fold: 0
cv:
  random_state: 0
  test_size: 0.1
bootstrap:
  random_state: 0
  replace: true
defaults:
  - task: rank_and_validate
  - ranker: chi2
  - validator: dt
  - datasrc: iris
  - cv: train_test_split