project: toy-wandb-fs
task:
  bootseed: 0
  fold: 0
cv:
  random_state: 0
  test_size: 0.1
pipeline:
  - task/ranker/chi2
  - task/ranker/chi2fs
defaults:
  - task: rank
  - task/ranker: chi2
  - datasrc: iris
  - cv: train_test_split